CUDA_VISIBLE_DEVICES=1 python vla-scripts/finetune.py \
  --vla_path /data1/model_weight/pretrain_weight/openvla/openvla-7b \
  --data_root_dir /data1/workspace/wxl/data/ \
  --dataset_name libero_spatial_no_noops \
  --run_root_dir /data1/workspace/huqiong/openvla-oft \
  --use_l1_regression True \
  --use_diffusion False \
  --use_film False \
  --num_images_in_input 2 \
  --use_proprio True \
  --batch_size 8 \
  --learning_rate 5e-4 \
  --num_steps_before_decay 100000 \
  --max_steps 150005 \
  --save_freq 10000 \
  --save_latest_checkpoint_only False \
  --image_aug True \
  --lora_rank 32 \
  --wandb_entity ruijia \
  --wandb_project openvla \
  --run_id_note parallel_dec--8_acts_chunk--continuous_acts--L1_regression--3rd_person_img--wrist_img--proprio_state_0520
